"""Add specialty to registration_requests

Revision ID: 060130e28939
Revises: 3ad3952d502f
Create Date: 2026-01-15 20:11:51.318698

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '060130e28939'
down_revision: Union[str, Sequence[str], None] = '3ad3952d502f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('registration_requests', sa.Column('specialty', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('registration_requests', 'specialty')
    # ### end Alembic commands ###
