"""Sync registration requests schema

Revision ID: 3ad3952d502f
Revises: cef5bff4c41d
Create Date: 2026-01-15 19:58:38.293562

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ad3952d502f'
down_revision: Union[str, Sequence[str], None] = 'cef5bff4c41d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('incomes', sa.Column('bank_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'incomes', 'bank_accounts', ['bank_account_id'], ['id'])
    op.add_column('registration_requests', sa.Column('payment_account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'registration_requests', 'bank_accounts', ['payment_account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'registration_requests', type_='foreignkey')
    op.drop_column('registration_requests', 'payment_account_id')
    op.drop_constraint(None, 'incomes', type_='foreignkey')
    op.drop_column('incomes', 'bank_account_id')
    # ### end Alembic commands ###
