"""Add academic module tables refined

Revision ID: 51e180cdcd63
Revises: 060130e28939
Create Date: 2026-01-22 01:36:20.059904

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '51e180cdcd63'
down_revision: Union[str, Sequence[str], None] = '060130e28939'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('academic_settings',
    sa.Column('key', sa.String(length=50), nullable=False),
    sa.Column('value', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('rubrics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('work_type', sa.String(length=50), nullable=False),
    sa.Column('max_score', sa.Float(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rubrics_id'), 'rubrics', ['id'], unique=False)
    op.create_table('jury_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('work_id', sa.String(), nullable=False),
    sa.Column('jury_user_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['jury_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['work_id'], ['research_works.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_jury_assignments_id'), 'jury_assignments', ['id'], unique=False)
    op.create_table('evaluations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('assignment_id', sa.Integer(), nullable=False),
    sa.Column('rubric_id', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['assignment_id'], ['jury_assignments.id'], ),
    sa.ForeignKeyConstraint(['rubric_id'], ['rubrics.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_evaluations_id'), 'evaluations', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_evaluations_id'), table_name='evaluations')
    op.drop_table('evaluations')
    op.drop_index(op.f('ix_jury_assignments_id'), table_name='jury_assignments')
    op.drop_table('jury_assignments')
    op.drop_index(op.f('ix_rubrics_id'), table_name='rubrics')
    op.drop_table('rubrics')
    op.drop_table('academic_settings')
    # ### end Alembic commands ###
