"""Add university to users

Revision ID: a504a0ae6d6b
Revises: 0ce5fda9903b
Create Date: 2026-01-15 00:49:51.978856

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a504a0ae6d6b'
down_revision: Union[str, Sequence[str], None] = '0ce5fda9903b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('courses', sa.Column('is_main_event', sa.Boolean(), nullable=True))
    op.add_column('courses', sa.Column('allowed_modality_ids', sa.JSON(), nullable=True))
    op.add_column('courses', sa.Column('linked_workshop_id', sa.Integer(), nullable=True))
    op.add_column('courses', sa.Column('content_data', sa.JSON(), nullable=True))
    op.add_column('courses', sa.Column('is_published', sa.Boolean(), nullable=True))
    op.drop_column('system_config', 'registration_modalities')
    op.drop_column('system_config', 'workshops')
    op.add_column('users', sa.Column('university', sa.String(), nullable=True))
    op.add_column('users', sa.Column('cmp_number', sa.String(), nullable=True))
    op.add_column('users', sa.Column('rne_number', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'rne_number')
    op.drop_column('users', 'cmp_number')
    op.drop_column('users', 'university')
    op.add_column('system_config', sa.Column('workshops', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.add_column('system_config', sa.Column('registration_modalities', postgresql.JSON(astext_type=sa.Text()), server_default=sa.text("'[]'::json"), autoincrement=False, nullable=True))
    op.drop_column('courses', 'is_published')
    op.drop_column('courses', 'content_data')
    op.drop_column('courses', 'linked_workshop_id')
    op.drop_column('courses', 'allowed_modality_ids')
    op.drop_column('courses', 'is_main_event')
    # ### end Alembic commands ###
