"""add_exam_id_to_program_activity

Revision ID: cbae204c2290
Revises: 51e180cdcd63
Create Date: 2026-01-22 11:46:31.032143

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cbae204c2290'
down_revision: Union[str, Sequence[str], None] = '51e180cdcd63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('program_activities', sa.Column('exam_id', sa.String(), nullable=True))
    op.create_foreign_key(None, 'program_activities', 'exams', ['exam_id'], ['id'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'program_activities', type_='foreignkey')
    op.drop_column('program_activities', 'exam_id')
    # ### end Alembic commands ###
