"""Add phone and residencyYear to users

Revision ID: cef5bff4c41d
Revises: a504a0ae6d6b
Create Date: 2026-01-15 00:58:16.249508

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cef5bff4c41d'
down_revision: Union[str, Sequence[str], None] = 'a504a0ae6d6b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.String(), nullable=True))
    op.add_column('users', sa.Column('residencyYear', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'residencyYear')
    op.drop_column('users', 'phone')
    # ### end Alembic commands ###
